version: '3'

services:
  # =MariaDB
  mariadb:
    image: phpcanister-mariadb:1.0.0
    build:
      context: ./mariadb
      args:
        - MARIADB_VERSION=${MARIADB_VERSION}
        - HOST_USER_UID=${HOST_USER_UID}
    ports:
      - "${MARIADB_HOST_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./data/mariadb:/var/lib/mysql:delegated"
  # =MySQL
  mysql:
    image: phpcanister-mysql:1.0.0
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
        - HOST_USER_UID=${HOST_USER_UID}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./data/mysql:/var/lib/mysql:delegated"
  # =nginx-PHP
  nginx-php:
    image: phpcanister-nginx-php:1.0.0
    build:
      context: ./nginx-php
      args:
        - HOST_USER_UID=${HOST_USER_UID}
        - APP_CODE_PATH_CONTAINER=${APP_CODE_PATH_CONTAINER}
    ports:
      - ${NGINX_HOST_PORT}:80
    volumes:
      - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}"
      - "./nginx-php/nginx/sites/:/etc/nginx/sites"
  redis:
    image: redis:${REDIS_VERSION}
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "./data/redis/:/data:delegated"
  # =memcached
  memcached:
    image: memcached:${MEMCACHED_VERSION}